### ISSUE TITLE
Clone function gives compile errors

### ISSUE THREAD

**Issue by MortenSchou** [petergjoel/ptrie#15]
I get compile errors here, when trying to use the copy constructor of a ptrie::map: 
https://github.com/petergjoel/ptrie/blob/a48ec2e4073e3a33260ac5da45387a2d6eab177f/src/ptrie/ptrie.h#L697-L699

**Comment by MortenSchou** [comment]
@petergjoel 
Take a look at this branch: https://github.com/MortenSchou/ptrie/tree/clone-bug
I added a test that produces the compile error in this commit: https://github.com/petergjoel/ptrie/commit/8cea7356a9bd82bf9077d5f3d9317727a377f344
I tried to fix it and the following segfault, but I don't know if it is correct...

**Comment by petergjoel** [comment]
@MortenSchou I assume we can close this issue now?

**Comment by MortenSchou** [comment]
Yes, this is solved by #18.
